### ISSUE TITLE
Erreur avec le binaire precompiller V1.2.0

### ISSUE THREAD

**Issue by akeiflin70** [triinoxys/RP42#1]
```
Unhandled exception: connect: No such file or directory (Errno)
  from __crystal_main
  from main
```

**Comment by alexandregv** [comment]
Hey, question bête mais tu as bien discord lancé ?
Et tu es bien à l'école ?

- Si non, alors désolé mais ça ne marche qu'à l'école (pour l'instant en tout cas).
- Si tu es bien à l'école, vérifie que ta variable $TMPDIR soit set. Elle devrait l'être par défaut et avoir une valeur du style `/var/folders/zz/zyxvpxvq6csfxvcn_n0003tvh021ypw/T/`, et ce dossier devrait contenir un fichier `discord-ipc-0`.
Tu peux vérifier ça avec cette commande: `ls $TMPDIR | grep discord`
Les autres variables possibles sont `$XDG_RUNTIME_DIR $TMP $TEMP` mais normalement à l'école ca devrait être `$TMPDIR`
Au pire indique moi ton login 42 et je passerai voir.

**Comment by akeiflin70** [comment]
Effectivement c'était bien une erreur du a Discord qui est fermer.

Tu pense que ce serrais possible d'avoir un binaire qui ne crash pas si Discord et off???
Psk du coup ça permettrais de programmer un run automatique du binaire au démarrage de la session!
Merci pour ta réponse!

**Comment by alexandregv** [comment]
La connexion RP42 <--> Discord se fait via IPC (le fameux fichier), je pourrais check si il existe d'abord pour éviter de crash pour fichier introuvable mais quel serait l’intérêt de lancer RP42 s'il ne fait rien ?

Le plus simple je pense serait dans ton script de d'abord check si `$TMPDIR/discord-ipc-0` existe, et de ne lancer RP42 que s'il existe bien (et donc que Discord est lancé) ou d'attendre que Discord se lance pour lancer RP42.
