### ISSUE TITLE
Compatibilité Linux 

### ISSUE THREAD

**Issue by Vusk42** [triinoxys/RP42#20]
Bonjour,
Je suis actuellement à 42 Angouleme et nous sommes sous Linux.
Est-il possible de rendre compatible ce Discord Rich Presence integration avec Linux  #?

**Comment by alexandregv** [comment]
Bonjour,
Il est utilisable sous linux, il y a une règle "linux" dans le Makefile.
Je n'ai pas udpate le code depuis un moment mais des studs l'utilisent à Paris, sous Linux.

**Comment by alexandregv** [comment]
Il pouvait y avoir un soucis avec le paquet libindicator, c'est normallement résolu dans le dernier commit.
