### ISSUE TITLE
Probleme avec le Makefile

### ISSUE THREAD

**Issue by PetitHommeLeVrai** [triinoxys/RP42#21]
Bonjour, j'essaie d'executer le makefile mais une erreur s'affiche:

```
-e Linux	[⏳ ]
# pkg-config --cflags  -- gtk+-3.0 appindicator3-0.1
Package appindicator3-0.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `appindicator3-0.1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'appindicator3-0.1' found
pkg-config: exit status 1
make: *** [Makefile:33: linux] Error 2
```

Comment regler cette erreur ?

**Comment by error7404** [comment]
same issue with debian 11 the probleme was that they changed appinidcator3-1 to libayatana-appindicator3-1 and to fix it you just need to update the module `systray` by running
```sh
go get github.com/getlantern/systray
```
in the RP42 folder before running `make`

**Comment by alexandregv** [comment]
Hi, I just updated the systray module.
